
ALTER SESSION SET CONTAINER = ORCLDBPDB1;


CREATE USER sinhvien01 IDENTIFIED BY password;
CREATE USER sinhvien02 IDENTIFIED BY password;
CREATE USER sinhvien03 IDENTIFIED BY password;
CREATE USER sinhvien04 IDENTIFIED BY password;
CREATE USER sinhvien05 IDENTIFIED BY password;
CREATE USER sinhvien06 IDENTIFIED BY password;
CREATE USER sinhvien07 IDENTIFIED BY password;
CREATE USER sinhvien08 IDENTIFIED BY password;
CREATE USER sinhvien09 IDENTIFIED BY password;
CREATE USER sinhvien10 IDENTIFIED BY password;
CREATE USER sinhvien11 IDENTIFIED BY password;
CREATE USER sinhvien12 IDENTIFIED BY password;
CREATE USER sinhvien13 IDENTIFIED BY password;
CREATE USER sinhvien14 IDENTIFIED BY password;
CREATE USER sinhvien15 IDENTIFIED BY password;
CREATE USER sinhvien16 IDENTIFIED BY password;
CREATE USER sinhvien17 IDENTIFIED BY password;
CREATE USER sinhvien18 IDENTIFIED BY password;
CREATE USER sinhvien19 IDENTIFIED BY password;
CREATE USER sinhvien20 IDENTIFIED BY password;

CREATE ROLE Role_QUANTRI;
CREATE ROLE Role_NGUOIDUNG;

GRANT CONNECT, RESOURCE, OEM_MONITOR, DBA TO Role_QUANTRI;
GRANT CONNECT, RESOURCE, OEM_MONITOR TO Role_NGUOIDUNG;


GRANT Role_QUANTRI TO sinhvien01;
GRANT Role_QUANTRI TO sinhvien02;
GRANT Role_QUANTRI TO sinhvien03;
GRANT Role_QUANTRI TO sinhvien04;
GRANT Role_QUANTRI TO sinhvien05;
GRANT Role_QUANTRI TO sinhvien06;
GRANT Role_QUANTRI TO sinhvien07;
GRANT Role_QUANTRI TO sinhvien08;
GRANT Role_QUANTRI TO sinhvien09;
GRANT Role_QUANTRI TO sinhvien10;

GRANT Role_NGUOIDUNG TO sinhvien11;
GRANT Role_NGUOIDUNG TO sinhvien12;
GRANT Role_NGUOIDUNG TO sinhvien13;
GRANT Role_NGUOIDUNG TO sinhvien14;
GRANT Role_NGUOIDUNG TO sinhvien15;
GRANT Role_NGUOIDUNG TO sinhvien16;
GRANT Role_NGUOIDUNG TO sinhvien17;
GRANT Role_NGUOIDUNG TO sinhvien18;
GRANT Role_NGUOIDUNG TO sinhvien19;
GRANT Role_NGUOIDUNG TO sinhvien20;

SELECT * FROM all_users;

SELECT * FROM DBA_ROLES;
