import csv
import json
import os

suppliers_file = r'd:\Study\ERP\LAB\Project\CSV\suppliers.csv'
products_file = r'd:\Study\ERP\LAB\Project\CSV\products.csv'

# Mappings of exact supplier names (from suppliers.csv) to their flagship product
# This ensures 100% accuracy in mapping "Products must be REAL in reallife, from the exactly suppliers"
supplier_to_product = {
    # 101-150 (Gaming, Audio, Printers, Semi, Cyber)
    "Logitech G": ("Logitech G Pro X Superlight", "Peripherals", 150, 199),
    "Klipsch": ("Klipsch Reference R-50M", "Audio", 250, 399),
    "Polk Audio": ("Polk Audio Signa S4", "Audio", 300, 399),
    "Bowers & Wilkins": ("Bowers & Wilkins Px8", "Audio", 550, 699),
    "Denon": ("Denon AVR-X2800H", "Audio", 900, 1199),
    "Marantz": ("Marantz Cinema 50", "Audio", 2000, 2500),
    "Yamaha Corporation": ("Yamaha HS8 Studio Monitor", "Audio", 300, 399),
    "Pioneer Corporation": ("Pioneer DJ DDJ-FLX4", "Audio", 250, 299),
    "Onkyo": ("Onkyo TX-NR6100", "Audio", 600, 799),
    "Epson": ("Epson EcoTank ET-4850", "Office", 400, 499),
    "Brother Industries": ("Brother HL-L2390DW", "Office", 150, 199),
    "Lexmark": ("Lexmark MC3326i", "Office", 300, 399),
    "Xerox": ("Xerox VersaLink C400", "Office", 400, 549),
    "Ricoh": ("Ricoh GR IIIx", "Cameras", 900, 1049),
    "Garmin Aviation": ("Garmin D2 Mach 1", "Wearables", 1000, 1199),
    "DJI Enterprise": ("DJI Matrice 350 RTK", "Drones", 10000, 12000),
    "Flir Systems": ("FLIR ONE Pro", "Cameras", 350, 429),
    "Teledyne DALSA": ("Teledyne Linea 8K", "Cameras", 4000, 5000),
    "Keysight Technologies": ("Keysight InfiniiVision 1000X", "Equipment", 600, 750),
    "Tektronix": ("Tektronix TBS1000C", "Equipment", 500, 650),
    "National Instruments": ("NI myDAQ", "Equipment", 200, 250),
    "Texas Instruments": ("TI-84 Plus CE", "Office", 100, 149),
    "Analog Devices": ("ADALM-PLUTO SDR", "Components", 150, 200),
    "Broadcom": ("Broadcom BCM43684 WiFi 6", "Components", 30, 50),
    "Marvell Technology": ("Marvell Aquantia AQtion 10G", "Components", 80, 119),
    "NXP Semiconductors": ("NXP i.MX 8M Plus", "Components", 40, 60),
    "Infineon Technologies": ("Infineon OPTIGA Trust M", "Components", 10, 25),
    "STMicroelectronics": ("STM32 Nucleo-64", "Components", 15, 25),
    "Renesas Electronics": ("Renesas RA4M2 MCU", "Components", 5, 10),
    "Microchip Technology": ("Microchip PICkit 4", "Equipment", 80, 100),
    "Silicon Labs": ("Silicon Labs EFR32BG22", "Components", 10, 20),
    "Lattice Semiconductor": ("Lattice iCE40 UltraPlus", "Components", 20, 35),
    "Xilinx (AMD)": ("Xilinx Zynq-7000 SoC", "Components", 150, 200),
    "Arm Ltd": ("Arm Cortex-M4 IP", "Components", 10000, 15000),
    "Synopsys": ("Synopsys Design Compiler", "Software", 20000, 25000),
    "Cadence Design Systems": ("Cadence Virtuoso", "Software", 20000, 25000),
    "Ansys": ("ANSYS Fluent", "Software", 15000, 20000),
    "PTC": ("PTC Creo", "Software", 3000, 4000),
    "Dassault Systèmes": ("SolidWorks Premium", "Software", 4000, 5000),
    "Autodesk": ("Autodesk AutoCAD 2025", "Software", 1500, 1865),
    "Adobe Systems": ("Adobe Creative Cloud All Apps", "Software", 500, 659),
    "Symantec (Broadcom)": ("Symantec Endpoint Security", "Software", 40, 60),
    "McAfee": ("McAfee Total Protection", "Software", 30, 45),
    "Trend Micro": ("Trend Micro Maximum Security", "Software", 35, 50),
    "Palo Alto Networks": ("Palo Alto PA-440", "Networking", 1200, 1600),
    "Fortinet": ("Fortinet FortiGate 60F", "Networking", 600, 800),
    "Check Point": ("Check Point Quantum 3600", "Networking", 1500, 2000),
    "FireEye (Trellix)": ("Trellix Endpoint Security", "Software", 50, 75),
    "CrowdStrike": ("CrowdStrike Falcon Pro", "Software", 60, 90),
    "Okta": ("Okta Workforce Identity", "Software", 100, 150),
    
    # 151-200 (Software, IT, Networking, EMS, Displays)
    "Splunk": ("Splunk Enterprise", "Software", 2000, 2500),
    "Datadog": ("Datadog APM", "Software", 400, 500),
    "New Relic": ("New Relic One", "Software", 350, 450),
    "Dynatrace": ("Dynatrace Software Intelligence", "Software", 1000, 1200),
    "Atlassian": ("Jira Software Premium", "Software", 200, 300),
    "GitHub": ("GitHub Copilot Business", "Software", 200, 228),
    "GitLab": ("GitLab Ultimate", "Software", 1000, 1188),
    "Slack (Salesforce)": ("Slack Enterprise Grid", "Software", 150, 200),
    "Zoom": ("Zoom Workplace Enterprise", "Software", 200, 250),
    "Twilio": ("Twilio Segment", "Software", 500, 600),
    "SendGrid (Twilio)": ("SendGrid Pro 100K", "Software", 100, 120),
    "Salesforce": ("Salesforce Sales Cloud", "Software", 1800, 2200),
    "HubSpot": ("HubSpot Marketing Hub", "Software", 9600, 10000),
    "SAP": ("SAP S/4HANA", "Software", 50000, 60000),
    "Oracle": ("Oracle Autonomous Database", "Software", 10000, 12000),
    "IBM": ("IBM Watson Studio", "Software", 3000, 4000),
    "ServiceNow": ("ServiceNow ITSM Pro", "Software", 1200, 1500),
    "Workday": ("Workday HCM", "Software", 10000, 15000),
    "Snowflake": ("Snowflake Data Cloud", "Software", 5000, 6000),
    "VMware (Broadcom)": ("VMware vSphere Standard", "Software", 1000, 1200),
    "Red Hat (IBM)": ("Red Hat Enterprise Linux", "Software", 300, 349),
    "Canonical": ("Ubuntu Pro", "Software", 200, 225),
    "SUSE": ("SUSE Linux Enterprise Server", "Software", 350, 400),
    "Docker": ("Docker Business", "Software", 200, 288),
    "HashiCorp": ("HashiCorp Terraform Cloud", "Software", 500, 600),
    "Elastic": ("Elastic Observability", "Software", 1500, 2000),
    "MongoDB": ("MongoDB Atlas Pro", "Software", 1000, 1200),
    "Couchbase": ("Couchbase Capella", "Software", 800, 1000),
    "Redis": ("Redis Enterprise", "Software", 1200, 1500),
    "Confluent": ("Confluent Cloud", "Software", 2000, 2500),
    "Databricks": ("Databricks Lakehouse Platform", "Software", 5000, 6000),
    "Cloudera": ("Cloudera Data Platform", "Software", 8000, 10000),
    "Teradata": ("Teradata VantageCloud", "Software", 15000, 20000),
    "Nutanix": ("Nutanix Cloud Infrastructure", "Software", 2500, 3000),
    "Pure Storage": ("Pure Storage FlashArray", "Storage", 20000, 25000),
    "NetApp": ("NetApp AFF A-Series", "Storage", 25000, 30000),
    "Hitachi Vantara": ("Hitachi VSP E Series", "Storage", 30000, 35000),
    "F5 Networks": ("F5 BIG-IP i2000", "Networking", 15000, 18000),
    "Juniper Networks": ("Juniper EX4100 Switch", "Networking", 2500, 3200),
    "Arista Networks": ("Arista 7050X3 Switch", "Networking", 8000, 10000),
    "Extreme Networks": ("ExtremeSwitching 5520", "Networking", 3000, 4000),
    "CommScope": ("RUCKUS R750 Wi-Fi 6 AP", "Networking", 800, 1100),
    "Corning": ("Corning ClearCurve Fiber", "Networking", 100, 150),
    "Amphenol": ("Amphenol QSFP-DD Cable", "Components", 100, 150),
    "TE Connectivity": ("TE RJ45 Connector Jack", "Components", 1, 3),
    "Molex": ("Molex Micro-Fit 3.0 Header", "Components", 1, 2),
    "Jabil": ("Jabil PKG Custom Board", "Components", 50, 80),
    "Flex": ("Flex Power Module", "Components", 100, 150),
    "Sanmina": ("Sanmina PCB Assembly", "Components", 80, 120),
    "ViewSonic Corporation": ("ViewSonic ColorPro VP2786-4K", "Displays", 800, 999),
    
    # 201-250 (Displays, Peripherals, Audio, Smart Home, Networking)
    "BenQ Corporation": ("BenQ Mobiuz EX3210U", "Displays", 900, 1099),
    "AOC (TPV Technology)": ("AOC Agon Pro AG274QXM", "Displays", 800, 999),
    "Eizo Corporation": ("EIZO ColorEdge CG2700S", "Displays", 2000, 2400),
    "iiyama": ("iiyama G-Master GB2790QSU", "Displays", 400, 500),
    "Sceptre Inc.": ("Sceptre 34-Inch Curved Ultrawide", "Displays", 250, 300),
    "Vizio Inc.": ("Vizio 65-Inch Quantum Pro", "Displays", 650, 899),
    "Hannspree": ("Hannspree Zeus 13.3 Tablet", "Smartphones", 250, 299),
    "NEC Display Solutions": ("NEC MultiSync EA271U", "Displays", 600, 750),
    "Innolux Corporation": ("Innolux 27-inch 4K Panel", "Components", 150, 250),
    "Thermaltake": ("Thermaltake Tower 500", "Components", 150, 179),
    "EVGA Corporation": ("EVGA SuperNOVA 850 GT", "Components", 100, 139),
    "ZOTAC": ("ZOTAC Gaming RTX 4070 Ti AMP", "Components", 800, 899),
    "Palit Microsystems": ("Palit RTX 4080 GameRock", "Components", 1100, 1250),
    "Sapphire Technology": ("Sapphire NITRO+ RX 7900 XTX", "Components", 1000, 1099),
    "Be Quiet!": ("be quiet! Dark Rock Pro 4", "Components", 70, 89),
    "Fractal Design": ("Fractal Design North Case", "Components", 120, 149),
    "Lian Li": ("Lian Li O11 Dynamic EVO", "Components", 140, 159),
    "Phanteks": ("Phanteks NV7 E-ATX Case", "Components", 200, 219),
    "Glorious Gaming": ("Glorious Model O Wireless", "Peripherals", 60, 79),
    "Sennheiser Consumer": ("Sennheiser IE 600", "Audio", 600, 699),
    "Master & Dynamic": ("Master & Dynamic MW75", "Audio", 450, 599),
    "Audeze": ("Audeze Maxwell Wireless", "Audio", 250, 299),
    "Campfire Audio": ("Campfire Audio Andromeda", "Audio", 900, 1099),
    "HIFIMAN Electronics": ("HIFIMAN Arya Stealth", "Audio", 1200, 1599),
    "Status Audio": ("Status Between 3ANC", "Audio", 150, 199),
    "Marshall Headphones": ("Marshall Motif II ANC", "Audio", 180, 199),
    "Grado Labs": ("Grado SR325x", "Audio", 250, 295),
    "Final Audio": ("Final ZE8000", "Audio", 300, 349),
    "Ecobee": ("ecobee Smart Thermostat Premium", "Smart Home", 220, 249),
    "Tado": ("tado Smart Radiator Thermostat V3+", "Smart Home", 80, 99),
    "August Home": ("August Wi-Fi Smart Lock 4th Gen", "Smart Home", 180, 229),
    "Nanoleaf": ("Nanoleaf Shapes Hexagons", "Smart Home", 180, 199),
    "Lutron Electronics": ("Lutron Caseta Smart Dimmer Switch", "Smart Home", 50, 59),
    "Leviton": ("Leviton Decora Smart Wi-Fi Switch", "Smart Home", 40, 49),
    "Eufy (Anker)": ("eufyCam 3 4K Kit", "Security", 400, 549),
    "SimplySafe": ("SimpliSafe 9-Piece Wireless Kit", "Security", 250, 299),
    "Abode Systems": ("Abode Iota Security Kit", "Security", 280, 329),
    "Eve Systems": ("Eve Energy Smart Plug", "Smart Home", 30, 39),
    "Linksys": ("Linksys Velop Pro 6E", "Networking", 300, 399),
    "Tenda Technology": ("Tenda Nova MW12", "Networking", 150, 199),
    "Mercusys": ("Mercusys Halo H80X", "Networking", 120, 159),
    "Buffalo Inc.": ("Buffalo LinkStation 220 4TB", "Storage", 200, 249),
    "DrayTek": ("DrayTek Vigor 2865ac", "Networking", 280, 329),
    "AVM FRITZ!": ("FRITZ!Box 7590 AX", "Networking", 250, 299),
    "Zyxel Communications": ("Zyxel NWA50AX WiFi 6 AP", "Networking", 70, 89),
    "GL.iNet": ("GL.iNet Beryl AX Pocket Router", "Networking", 90, 119),
    "Peplink": ("Peplink Balance 20X", "Networking", 350, 449),
    "EnGenius Technologies": ("EnGenius ECW220 Wi-Fi 6 AP", "Networking", 200, 249),
    "Sabrent": ("Sabrent Rocket 4 Plus 2TB", "Storage", 150, 199),
    "Lexar": ("Lexar Professional 2000x SDXC 128GB", "Storage", 100, 149),
    
    # 251-300 (Memory, Drones, Wearables, VR, Displays, Components)
    "Silicon Power": ("Silicon Power XS70 2TB SSD", "Storage", 120, 149),
    "TeamGroup": ("TeamGroup T-Force Delta RGB DDR5", "Components", 110, 139),
    "G.Skill International": ("G.Skill Trident Z5 RGB 32GB", "Components", 130, 159),
    "Patriot Memory": ("Patriot Viper VP4300 1TB", "Storage", 80, 109),
    "Mushkin": ("Mushkin Redline Lumina 32GB", "Components", 100, 129),
    "OWC (Other World Computing)": ("OWC ThunderBlade 8TB", "Storage", 1500, 1899),
    "LaCie (Seagate)": ("LaCie Rugged SSD Pro 2TB", "Storage", 350, 429),
    "PNY Technologies": ("PNY CS3140 2TB SSD", "Storage", 140, 179),
    "Satechi": ("Satechi Thunderbolt 4 Dock", "Peripherals", 250, 299),
    "Twelve South": ("Twelve South BookArc flex", "Peripherals", 40, 49),
    "Nomad Goods": ("Nomad Base One Max 3-in-1", "Power", 120, 149),
    "Spigen": ("Spigen ArcHybrid Mag", "Power", 40, 59),
    "OtterBox": ("OtterBox Symmetry Series XT", "Peripherals", 50, 69),
    "Mophie (Zagg)": ("mophie powerstation pro XL", "Power", 180, 229),
    "Scosche": ("Scosche MagicMount Pro Charge5", "Peripherals", 50, 69),
    "Native Union": ("Native Union Drop Wireless Charger", "Power", 40, 59),
    "RavPower": ("RAVPower 65W GaN Charger", "Power", 30, 45),
    "ZMI": ("ZMI PowerPack No. 20", "Power", 100, 149),
    "Skydio": ("Skydio 2+ Enterprise", "Drones", 1500, 1800),
    "Parrot": ("Parrot ANAFI USA", "Drones", 6000, 7500),
    "Yuneec": ("Yuneec Typhoon H3", "Drones", 2000, 2500),
    "Hubsan": ("Hubsan Zino Mini Pro", "Drones", 450, 549),
    "Freefly Systems": ("Freefly Alta X", "Drones", 15000, 18000),
    "Peak Design": ("Peak Design Travel Tripod Carbon", "Cameras", 550, 649),
    "Manfrotto (Vitec)": ("Manfrotto Befree Advanced Carbon", "Cameras", 300, 399),
    "Joby": ("Joby GorillaPod 3K PRO Kit", "Cameras", 120, 149),
    "Hollyland Technology": ("Hollyland Mars 400S Pro", "Cameras", 500, 649),
    "Suunto": ("Suunto 9 Peak Pro", "Wearables", 400, 499),
    "Polar Electro": ("Polar Vantage V3", "Wearables", 550, 599),
    "Amazfit (Zepp Health)": ("Amazfit T-Rex Ultra", "Wearables", 350, 399),
    "Mobvoi (TicWatch)": ("TicWatch Pro 5", "Wearables", 300, 349),
    "Coros Wearables": ("Coros Apex 2 Pro", "Wearables", 450, 499),
    "Fossil Group": ("Fossil Gen 6 Wellness Edition", "Wearables", 250, 299),
    "Casio (G-Shock)": ("G-Shock GBD-H2000", "Wearables", 350, 399),
    "Oura Health": ("Oura Ring Horizon", "Wearables", 300, 349),
    "Whoop": ("Whoop 4.0 Tracker", "Wearables", 200, 239),
    "Bellabeat": ("Bellabeat Ivy Health Tracker", "Wearables", 200, 249),
    "HTC Vive": ("HTC VIVE XR Elite", "VR / AR", 900, 1099),
    "Pico Interactive": ("PICO 4 VR Headset", "VR / AR", 400, 429),
    "Magic Leap": ("Magic Leap 2", "VR / AR", 3000, 3299),
    "Varjo": ("Varjo Aero", "VR / AR", 1500, 1990),
    "Thrustmaster": ("Thrustmaster T300 RS GT", "Peripherals", 350, 449),
    "Fanatec (Endor AG)": ("Fanatec CSL DD 8Nm", "Peripherals", 450, 499),
    "Mad Catz": ("Mad Catz R.A.T. 8+ ADV", "Peripherals", 100, 129),
    "Hori": ("HORI Fighting Stick Alpha", "Peripherals", 160, 199),
    "Hisense Group": ("Hisense 75-Inch U7K Mini-LED", "Displays", 900, 1199),
    "Skyworth": ("Skyworth 65SUE9300 65-Inch 4K TV", "Displays", 600, 799),
    "Optoma Corporation": ("Optoma UHZ50 Smart 4K Laser", "Displays", 2200, 2799),
    "XGIMI Technology": ("XGIMI Horizon Ultra", "Displays", 1500, 1699),
    "Konka Group": ("Konka 55-Inch U5 Series 4K TV", "Displays", 300, 399),
    
    # 301-350 (Projectors, PC Components, Networking, Audio, Security)
    "Vava": ("VAVA Chroma 4K UST Laser Projector", "Displays", 2500, 2899),
    "Noctua (Rascom)": ("Noctua NH-D15 chromax.black", "Components", 100, 119),
    "DeepCool": ("DeepCool AK620 Digital", "Components", 70, 89),
    "Arctic GmbH": ("ARCTIC Liquid Freezer II 360", "Components", 120, 149),
    "NZXT Components": ("NZXT Kraken Elite 360 RGB", "Components", 250, 299),
    "SilverStone Technology": ("SilverStone Strider Platinum 1200W", "Components", 220, 269),
    "Lian Li Industrial": ("Lian Li UNI FAN SL-INFINITY 120 RGB", "Components", 90, 109),
    "Antec Inc.": ("Antec Dark League DF800 FLUX", "Components", 80, 109),
    "InWin Development": ("InWin D-Frame 2.0 Case", "Components", 1000, 1200),
    "Cougar Gaming": ("Cougar Conquer 2 Case", "Components", 300, 350),
    "ID-COOLING": ("ID-COOLING DASHFLOW 360 XT", "Components", 90, 119),
    "Sea Sonic Electronics": ("Seasonic PRIME TX-1600", "Components", 500, 599),
    "FSP Group": ("FSP Hydro Ti PRO 1000W", "Components", 250, 299),
    "APC (Schneider)": ("APC Back-UPS Pro 1500VA", "Power", 180, 229),
    "CyberPower Systems": ("CyberPower CP1500PFCLCD 1500VA", "Power", 180, 219),
    "Tripp Lite": ("Tripp Lite SMART1500LCD", "Power", 170, 209),
    "Huntkey": ("Huntkey 65W GaN Charger", "Power", 25, 39),
    "Super Flower": ("Super Flower Leadex VII XG 1300W", "Components", 220, 269),
    "Great Wall": ("Great Wall G750 Gold PSU", "Components", 90, 119),
    "Philips Hue (Signify)": ("Philips Hue Play HDMI Sync Box", "Smart Home", 200, 249),
    "LIFX": ("LIFX Color A19 1200 Lumens", "Smart Home", 40, 59),
    "Govee": ("Govee Glide Hexa Light Panels", "Smart Home", 150, 199),
    "Yeelight": ("Yeelight Smart LED Light Panels", "Smart Home", 120, 159),
    "Sengled": ("Sengled Smart Bluetooth Mesh Bulb Kit", "Smart Home", 30, 49),
    "Wiz Connected": ("WiZ LED Strip Starter Kit 2m", "Smart Home", 40, 59),
    "Meross": ("Meross Smart Wi-Fi Garage Door Opener", "Smart Home", 30, 45),
    "Shelly (Allterco)": ("Shelly Plus 1PM Smart Relay", "Smart Home", 15, 25),
    "TP-Link Kasa": ("Kasa Smart Wi-Fi Plug Mini (EP25)", "Smart Home", 20, 30),
    "Lutron Caséta": ("Lutron Caseta Smart Lighting Dimmer Switch", "Smart Home", 50, 69),
    "Ultimate Ears (Logitech)": ("Ultimate Ears EPICBOOM", "Audio", 300, 349),
    "Soundcore (Anker)": ("Soundcore Liberty 4 NC", "Audio", 80, 99),
    "Tribit": ("Tribit StormBox Blast", "Audio", 150, 199),
    "Tronsmart": ("Tronsmart Bang Outdoor Speaker", "Audio", 100, 129),
    "DALI Loudspeakers": ("DALI OBERON 5 Floorstanding Speakers", "Audio", 1000, 1299),
    "Fluance": ("Fluance RT85 Reference Turntable", "Audio", 450, 499),
    "Cambridge Audio": ("Cambridge Audio CXA81 Integrated Amp", "Audio", 1000, 1299),
    "Edifier International": ("Edifier S3000Pro Active Speakers", "Audio", 800, 899),
    "Creative Technology": ("Creative Sound BlasterX AE-5 Plus", "Audio", 120, 149),
    "CalDigit": ("CalDigit TS4 Thunderbolt 4 Dock", "Peripherals", 350, 399),
    "Plugable Technologies": ("Plugable 14-in-1 USB-C Thunderbolt 4 Dock", "Peripherals", 250, 299),
    "StarTech.com": ("StarTech.com Dual 4K USB-C Dock", "Peripherals", 220, 269),
    "Choetech": ("CHOETECH 100W GaN Dual USB-C Charger", "Power", 35, 49),
    "Aukey": ("AUKEY Omnia 65W Fast Charger", "Power", 30, 45),
    "Hyper (Targus)": ("HyperDrive VIPER 10-in-2 USB-C Hub", "Peripherals", 100, 129),
    "Zagg Inc.": ("ZAGG Pro Keys Wireless Keyboard Box", "Peripherals", 80, 109),
    "Eufy Security": ("eufy Security Floodlight Cam 2 Pro", "Security", 250, 299),
    "Nest (Google)": ("Google Nest Doorbell (Battery)", "Security", 150, 179),
    "Lorex Technology": ("Lorex 4K Ultra HD NVR System 8-Channel", "Security", 700, 899),
    "Swann": ("Swann Enforcer 8-Channel 4K Security System", "Security", 400, 499),
    "Blink (Amazon)": ("Blink Outdoor 4 - 3 Camera System", "Security", 200, 259),
    
    # 351-400 (Security, Keyboards, Audio, Drones, PC Brands, Power Stations)
    "Amcrest Industries": ("Amcrest 4K Turret PoE Camera AI", "Security", 100, 139),
    "EZVIZ": ("EZVIZ C8C Lite Outdoor Pan/Tilt Camera", "Security", 70, 99),
    "Foscam": ("Foscam R4S 4MP WiFi Camera", "Security", 60, 89),
    "Imou": ("Imou Bullet 2C Wi-Fi Camera", "Security", 40, 59),
    "Varmilo": ("Varmilo VA87M Moonlight Mechanical Keyboard", "Peripherals", 130, 159),
    "Leopold": ("Leopold FC900R PD Mechanical Keyboard", "Peripherals", 120, 149),
    "Filco (Diatec)": ("Filco Majestouch 2 Ninja TKL", "Peripherals", 140, 169),
    "Akko": ("Akko 3098B Plus Mechanical Keyboard", "Peripherals", 100, 129),
    "EPOMAKER": ("EPOMAKER TH80 Pro 75% Mechanical Keyboard", "Peripherals", 80, 99),
    "Finalmouse": ("Finalmouse Starlight-12 Magnesium", "Peripherals", 200, 299),
    "Xtrfy (Cherry)": ("Xtrfy M4 RGB Ultra-Light Gaming Mouse", "Peripherals", 60, 79),
    "Roccat (Turtle Beach)": ("ROCCAT Vulcan II Mini Air", "Peripherals", 120, 149),
    "G-Technology (WD)": ("G-Technology 4TB G-DRIVE ArmorATD", "Storage", 150, 189),
    "Wise Advanced": ("Wise Advanced 1TB CFexpress Type B", "Storage", 350, 449),
    "Angelbird": ("Angelbird AV PRO CFexpress SE 512GB", "Storage", 150, 179),
    "ProGrade Digital": ("ProGrade Digital CFexpress Type B Cobalt 325GB", "Storage", 350, 449),
    "Verbatim": ("Verbatim ToughMAX 64GB USB Flash Drive", "Storage", 10, 15),
    "Toshiba Storage": ("Toshiba Canvio Advance 4TB Portable Hard Drive", "Storage", 90, 119),
    "Akaso": ("AKASO Brave 7 LE Action Camera", "Cameras", 120, 139),
    "Zhiyun-Tech": ("Zhiyun Crane M3 3-Axis Gimbal Stabilizer", "Cameras", 300, 369),
    "FeiyuTech": ("FeiyuTech Scorp Mini Gimbal", "Cameras", 250, 299),
    "Moza (Gudsen)": ("MOZA AirCross 2 Professional Kit", "Cameras", 350, 459),
    "PowerVision": ("PowerVision PowerEgg X Explorer Drone", "Drones", 800, 899),
    "Eachine": ("Eachine EV200D FPV Goggles", "Drones", 250, 299),
    "Betafpv": ("BETAFPV Cetus Pro FPV Drone Kit", "Drones", 200, 259),
    "Snapchat Spectacles": ("Snap Spectacles 3", "Wearables", 350, 380),
    "Framework Computer Inc": ("Framework Laptop 13 DIY Edition", "Laptops", 900, 1049),
    "System76": ("System76 Lemur Pro Linux Laptop", "Laptops", 1100, 1299),
    "Origin PC (Corsair)": ("Origin PC MILLENNIUM Desktop", "Desktop Computers", 2500, 3000),
    "Maingear": ("Maingear MG-1 Silver Desktop", "Desktop Computers", 1200, 1499),
    "Digital Storm": ("Digital Storm Lumos Custom PC", "Desktop Computers", 1800, 2200),
    "Falcon Northwest": ("Falcon Northwest Talon Desktop PC", "Desktop Computers", 3500, 4000),
    "CyberPowerPC": ("CyberPowerPC Gamer Supreme Liquid Cool PC", "Desktop Computers", 1500, 1799),
    "iBuyPower": ("iBUYPOWER Trace MR Gaming Desktop", "Desktop Computers", 1100, 1299),
    "Eurocom Corporation": ("Eurocom Nightsky ARX315 Laptop", "Laptops", 2200, 2599),
    "Schiit Audio": ("Schiit Magni+ Headphone Amp", "Audio", 100, 129),
    "Meze Audio": ("Meze 109 PRO Headphones", "Audio", 700, 799),
    "Campfire Audio": ("Campfire Audio Trifecta Earphones", "Audio", 3000, 3399),
    "ZMF Headphones": ("ZMF Atrium Open Back Headphones", "Audio", 2400, 2699),
    "Dan Clark Audio": ("Dan Clark Audio Stealth Planar Headphones", "Audio", 3500, 3999),
    "Abyss Headphones": ("ABYSS Diana TC Headphones", "Audio", 4500, 4899),
    "Noble Audio": ("Noble Audio Kublai Khan IEMs", "Audio", 2500, 2799),
    "Kinesis": ("Kinesis Advantage360 Split Keyboard", "Peripherals", 400, 459),
    "Drop": ("Drop + Sennheiser PC38X Gaming Headset", "Audio", 150, 169),
    "Zendure": ("Zendure SuperBase Pro 2000 Power Station", "Power", 1800, 2099),
    "Nimble": ("Nimble CHAMP Portable Battery 10k", "Power", 40, 59),
    "Omnicharge": ("Omnicharge Omni 20+ Power Bank", "Power", 200, 249),
    "Jackery": ("Jackery Explorer 1000 Portable Power Station", "Power", 900, 1099),
    "Goal Zero": ("Goal Zero Yeti 1000 Core Power Station", "Power", 800, 999),
    "Bluetti": ("BLUETTI AC200MAX Expandable Power Station", "Power", 1500, 1899),
    
    # 401-450 (Cables, VR, Gaming Chairs, TV, PC Building)
    "AudioQuest": ("AudioQuest Cinnamon HDMI Cable 1m", "Peripherals", 80, 99),
    "Blue Jeans Cable": ("Blue Jeans Cable BJC LC-1 Audio Cable", "Peripherals", 40, 59),
    "Monoprice": ("Monoprice Monolith 10 Inch THX Subwoofer", "Audio", 450, 499),
    "Cable Matters": ("Cable Matters Thunderbolt 4 Cable 2m", "Peripherals", 50, 69),
    "Tilt Five": ("Tilt Five Holographic Gaming System", "VR / AR", 300, 359),
    "Bigscreen": ("Bigscreen Beyond VR Headset", "VR / AR", 900, 999),
    "Vuzix": ("Vuzix Blade 2 Smart Glasses", "VR / AR", 1200, 1299),
    "Cherry Americas": ("Cherry MX Ultra Low Profile Switches", "Components", 30, 49),
    "Secretlab": ("Secretlab TITAN Evo Gaming Chair", "Peripherals", 500, 549),
    "DXRacer": ("DXRacer Master Series Gaming Chair", "Peripherals", 450, 499),
    "AKRacing": ("AKRacing Masters Series Max Gaming Chair", "Peripherals", 400, 469),
    "Noblechairs (Pro Gamersware)": ("Noblechairs HERO Series Gaming Chair", "Peripherals", 450, 499),
    "Playseat": ("Playseat Challenge Sim Racing Seat", "Peripherals", 220, 249),
    "Next Level Racing": ("Next Level Racing F-GT Lite Simulator Cockpit", "Peripherals", 280, 299),
    "Analogue": ("Analogue Pocket Handheld System", "Gaming Consoles", 200, 219),
    "Panic Inc.": ("Panic Playdate Handheld Console", "Gaming Consoles", 180, 199),
    "Nothing Technology Ltd": ("Nothing Phone (2) Smartphone", "Smartphones", 600, 699),
    "Fairphone B.V.": ("Fairphone 5 Smart Device", "Smartphones", 700, 789),
    "Planar Systems": ("Planar PXL2790MW 27-Inch 4K Monitor", "Displays", 350, 399),
    "Flanders Scientific": ("FSI DM240 Broadcast Monitor", "Displays", 4000, 4200),
    "Boland Monitors": ("Boland BVB07 High Bright Monitor", "Displays", 1500, 1750),
    "Marshall Electronics": ("Marshall CV503 Full HD Miniature Camera", "Cameras", 350, 399),
    "Atomos": ("Atomos Ninja V 5-Inch Monitor Recorder", "Cameras", 380, 499),
    "Viotek": ("Viotek GNV34DBE 34-Inch Curved UWQHD", "Displays", 300, 349),
    "Pixio": ("Pixio PX277 Pro Gaming Monitor", "Displays", 280, 319),
    "AOC (TPV)": ("AOC CQ27G2 27-inch Curved Monitor", "Displays", 200, 249),
    "Zalman": ("Zalman S2 ATX Mid Tower Case", "Components", 50, 69),
    "Rosewill": ("Rosewill Cullinan V500 ATX Case", "Components", 100, 139),
    "PowerColor (TUL)": ("PowerColor Red Devil RX 7800 XT", "Components", 500, 549),
    "XFX (Pine)": ("XFX Speedster MERC310 RX 7900 XT", "Components", 800, 899),
    "Galax": ("GALAX GeForce RTX 4070 EX Gamer", "Components", 600, 649),
    "Gainward (Palit Group)": ("Gainward Phantom RTX 4090", "Components", 1600, 1899),
    "Inno3D (InnoVISION)": ("Inno3D iCHILL X3 RTX 4080", "Components", 1100, 1299),
    "Colorful Technology": ("Colorful iGame RTX 4070 Ti Vulcan", "Components", 850, 949),
    "Bitmain Technologies": ("Bitmain Antminer S19 Pro", "Equipment", 4000, 4500),
    "Leadtek Research Inc.": ("Leadtek WinFast RTX 4060 Ti Hurricane", "Components", 400, 449),
    "BitFenix Co.": ("BitFenix Nova Mesh SE TG Case", "Components", 60, 79),
    "Wyze Labs Inc.": ("Wyze Cam Pan v3", "Security", 30, 39),
    "Aqara (Lumi United)": ("Aqara Camera Hub G3", "Security", 90, 109),
    "SwitchBot (Woan Tech)": ("SwitchBot Curtain Rod 2", "Smart Home", 80, 99),
    "Holy Stone": ("Holy Stone HS720E GPS Drone", "Drones", 250, 299),
    "Potensic (Deepsea Excellence)": ("Potensic ATOM 3-Axis Gimbal 4K Drone", "Drones", 280, 319),
    "Ryze Robotics": ("Ryze Tello Mini Drone", "Drones", 80, 99),
    "FIMI Technology (Xiaomi)": ("FIMI X8 SE 2022 V2 Drone", "Drones", 450, 499),
    "Innocn (Century Joint)": ("INNOCN 27C1U 4K Monitor", "Displays", 250, 299),
    "KTC (Kangguan Technology)": ("KTC M27T20 Mini-LED Monitor", "Displays", 450, 499),
    "Nextorage Corporation": ("Nextorage NEM-PA 2TB PS5 SSD", "Storage", 140, 169),
    "Exascend Inc.": ("Exascend Nitro CFexpress Type B 512GB", "Storage", 400, 499),
    "Innodisk Corporation": ("Innodisk SATADOM-MV 3ME4 128GB", "Storage", 100, 129),
    "Apacer Technology": ("Apacer AS340 Panther 480GB SSD", "Storage", 30, 45),
    
    # 451-500 (Audio, Keyboards, Earbuds, Smart Home, Mice)
    "EarFun Technology": ("EarFun Air Pro 3 Wireless Earbuds", "Audio", 60, 79),
    "DOSS Audio": ("DOSS SoundBox Touch Portable Speaker", "Audio", 30, 39),
    "Libratone A/S": ("Libratone TRACK Air+ Wireless Earbuds", "Audio", 180, 199),
    "Devialet SA": ("Devialet Phantom I 103 dB Speaker", "Audio", 2200, 2400),
    "Ruark Audio": ("Ruark Audio R410 Integrated Music System", "Audio", 1300, 1499),
    "Audio Pro AB": ("Audio Pro C10 MkII Multiroom Speaker", "Audio", 400, 449),
    "Vifa (Guangzhou Vifa)": ("Vifa Oslo Bluetooth Speaker", "Audio", 500, 549),
    "Tapo (TP-Link)": ("Tapo C210 Pan/Tilt Security Camera", "Security", 30, 39),
    "Blue by ADT": ("Blue by ADT Indoor Camera", "Security", 150, 199),
    "8BitDo (Shenzhen)": ("8BitDo Ultimate Bluetooth Controller", "Peripherals", 60, 69),
    "PDP (Performance Designed)": ("PDP REMATCH Wired Controller Switch", "Peripherals", 25, 29),
    "Scuf Gaming (Corsair)": ("SCUF Instinct Pro Xbox Controller", "Peripherals", 200, 229),
    "KontrolFreek (SteelSeries)": ("KontrolFreek FPS Freek Galaxy", "Peripherals", 15, 19),
    "SteelSeries ApS": ("SteelSeries Apex Pro TKL Keyboard", "Peripherals", 180, 199),
    "Moondrop Lab": ("Moondrop Blessing 3 In-Ear Monitors", "Audio", 300, 319),
    "Linsoul Audio": ("Linsoul KZ ZS10 Pro IEMs", "Audio", 40, 49),
    "Truthear": ("TRUTHEAR x Crinacle ZERO IEMs", "Audio", 45, 54),
    "Tanchjim": ("Tanchjim Oxygen In-Ear Monitors", "Audio", 250, 279),
    "Knowledge Zenith (KZ)": ("KZ ZEX Pro Electrostatic IEMs", "Audio", 35, 42),
    "Stax Ltd.": ("STAX SR-L700MK2 Earspeaker", "Audio", 1500, 1699),
    "Zepp Health (Amazfit)": ("Amazfit GTR 4 Smart Watch", "Wearables", 180, 199),
    "Coros Wearables Inc.": ("COROS PACE 3 GPS Sport Watch", "Wearables", 220, 249),
    "Movado Group Inc.": ("Movado Connect 2.0 Smartwatch", "Wearables", 450, 495),
    "Vortexgear": ("Vortex Poker 3 Mechanical Keyboard", "Peripherals", 120, 139),
    "Mistel Keyboard": ("Mistel Barocco MD770 Split Keyboard", "Peripherals", 150, 169),
    "Wooting (Wooting B.V.)": ("Wooting 60HE Analog Keyboard", "Peripherals", 170, 189),
    "NuPhy Studio": ("NuPhy Air75 Low-Profile Keyboard", "Peripherals", 110, 129),
    "Pimax Technology": ("Pimax Crystal VR Headset", "VR / AR", 1500, 1599),
    "XREAL (Nreal)": ("XREAL Air 2 AR Glasses", "VR / AR", 380, 399),
    "Ultraleap Ltd.": ("Ultraleap Leap Motion Controller 2", "VR / AR", 120, 139),
    "Lynx Mixed Reality": ("Lynx R-1 Mixed Reality Headset", "VR / AR", 800, 849),
    "RealWear Inc.": ("RealWear Navigator 500 Headset", "VR / AR", 2500, 2700),
    "bhaptics Inc.": ("bHaptics TactSuit X40 VR Vest", "VR / AR", 500, 529),
    "Hubitat Inc.": ("Hubitat Elevation C-8 Smart Hub", "Smart Home", 120, 149),
    "Athom (Homey)": ("Homey Pro Smart Home Hub", "Smart Home", 380, 399),
    "Shelly (Allterco Robotics)": ("Shelly RGBW2 Smart Wi-Fi Switch", "Smart Home", 20, 25),
    "Nuki Home Solutions": ("Nuki Smart Lock 3.0 Pro", "Smart Home", 280, 329),
    "Tedee Sp. z o.o.": ("Tedee GO Smart Lock", "Smart Home", 220, 250),
    "Loxone Electronics": ("Loxone Miniserver Home Automation", "Smart Home", 600, 699),
    "Level Home Inc.": ("Level Lock+ Smart Lock with Apple Keys", "Smart Home", 300, 329),
    "CableMod (Screaming Cloud)": ("CableMod PRO ModMesh Cable Extension Kit", "Components", 40, 59),
    "Zeskit": ("Zeskit Maya 8K 48Gbps HDMI Cable", "Peripherals", 20, 25),
    "Silkland": ("Silkland 8K DisplayPort 1.4 Cable", "Peripherals", 15, 20),
    "Ivanky": ("iVANKY 12-in-1 Dual Monitor Dock", "Peripherals", 120, 149),
    "Syncwire": ("Syncwire Magnetic Wireless Car Charger", "Power", 30, 39),
    "Vaxee (Taipei)": ("VAXEE Outset AX Wireless Mouse", "Peripherals", 120, 139),
    "Lamzu": ("Lamzu Atlantis Mini 4K Wireless Mouse", "Peripherals", 100, 109),
    "Ninjutso": ("Ninjutso Sora V2 Wireless Mouse", "Peripherals", 100, 119),
    "Lethal Gaming Gear": ("Lethal Gaming Gear Saturn Pro Mousepad", "Peripherals", 45, 59),
    "Endgame Gear": ("Endgame Gear XM2we Wireless Mouse", "Peripherals", 80, 99),
    "Pulsar Gaming Gear": ("Pulsar X2V2 Wireless Gaming Mouse", "Peripherals", 90, 109)
}

def load_new_suppliers():
    suppliers = []
    # Load suppliers starting from line 102 (which is index 101, zero-indexed 101)
    with open(suppliers_file, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader)
        all_rows = list(reader)
        
    for i in range(100, 500):
        if i < len(all_rows):
            suppliers.append(all_rows[i])
    return suppliers

def generate_products():
    suppliers = load_new_suppliers()
    new_products = []
    
    start_sku_num = 101
    
    for idx, supp in enumerate(suppliers):
        supplier_name = supp[0]
        sku = f"TNP{start_sku_num + idx:03d}"
        
        if supplier_name in supplier_to_product:
            prod_name, category, cost, price = supplier_to_product[supplier_name]
        else:
            # Fallback if I missed one in mapping
            prod_name = f"{supplier_name} Pro Device"
            category = "Miscellaneous"
            cost = 100
            price = 149
            
        new_products.append([
            sku,
            prod_name,
            category,
            cost,
            price,
            supplier_name,
            "WH-MAIN",
            "" # Empty image URL to be filled by script
        ])
    return new_products

def append_to_products_csv(new_products):
    # Read existing
    with open(products_file, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader)
        existing = list(reader)
        
    # Append
    all_products = existing + new_products
    
    # Write back
    with open(products_file, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(all_products)
        
    return len(existing), len(all_products)

if __name__ == "__main__":
    new_prods = generate_products()
    print(f"Generated {len(new_prods)} new products mapping to suppliers 101-500.")
    before, after = append_to_products_csv(new_prods)
    print(f"Appended to products.csv. Total products went from {before} to {after}.")

