CREATE DATABASE Assignment_05;

DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS INVOICE_DETAIL;


CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    FULL_NAME NVARCHAR(100) NOT NULL,
    ADDRESS NVARCHAR(255),
    PHONE NVARCHAR(20),
    DOB DATE,
    TOTAL_SALES DECIMAL(12, 2) DEFAULT 0,
    REG_DATE DATE NOT NULL
);


CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    FULL_NAME NVARCHAR(100) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    PHONE NVARCHAR(20)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME NVARCHAR(100) NOT NULL,
    UNIT NVARCHAR(20),
    COUNTRY_OF_ORIGIN NVARCHAR(50),
    PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE INVOICE (
    INVOICE_NO INT PRIMARY KEY,
    INVOICE_DATE DATE NOT NULL,
    CUSTOMER_ID INT,
    EMPLOYEE_ID INT NOT NULL,
    TOTAL_VALUE DECIMAL(12, 2) NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE INVOICE_DETAIL (
    INVOICE_NO INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (INVOICE_NO, PRODUCT_ID),
    FOREIGN KEY (INVOICE_NO) REFERENCES INVOICE(INVOICE_NO),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);


-- 1: Product price must be at least 500 VND
ALTER TABLE PRODUCT
ADD CONSTRAINT CK_PRODUCT_PRICE CHECK (PRICE >= 500);

-- 2: Customer registration date must be after their date of birth
ALTER TABLE CUSTOMER
ADD CONSTRAINT CK_CUSTOMER_REG_DATE CHECK (REG_DATE > DOB);

-- 3: Invoice date must be after customer registration date
ALTER TABLE INVOICE
ADD CONSTRAINT CK_INVOICE_DATE CHECK (
    INVOICE_DATE >= (SELECT REG_DATE FROM CUSTOMER WHERE CUSTOMER_ID = INVOICE.CUSTOMER_ID)
);

-- 4: Invoice date must be after employee hire date
ALTER TABLE INVOICE
ADD CONSTRAINT CK_INVOICE_EMP_HIRE_DATE CHECK (
    INVOICE_DATE >= (SELECT HIRE_DATE FROM EMPLOYEE WHERE EMPLOYEE_ID = INVOICE.EMPLOYEE_ID)
);

-- 5: Total sales of customer must equal sum of their invoices
GO
CREATE TRIGGER trg_update_customer_total_sales
ON INVOICE
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    UPDATE CUSTOMER
    SET TOTAL_SALES = (
        SELECT SUM(TOTAL_VALUE)
        FROM INVOICE
        WHERE CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
    )
    WHERE CUSTOMER_ID IN (
        SELECT CUSTOMER_ID FROM inserted
        UNION
        SELECT CUSTOMER_ID FROM deleted
    );
END;
GO

-- 6: Invoice total value must equal sum of quantity*price from details
GO
CREATE TRIGGER trg_update_invoice_total_value
ON INVOICE_DETAIL
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    UPDATE INVOICE
    SET TOTAL_VALUE = (
        SELECT SUM(ID.QUANTITY * P.PRICE)
        FROM INVOICE_DETAIL ID
        JOIN PRODUCT P ON ID.PRODUCT_ID = P.PRODUCT_ID
        WHERE ID.INVOICE_NO = INVOICE.INVOICE_NO
    )
    WHERE INVOICE_NO IN (
        SELECT INVOICE_NO FROM inserted
        UNION
        SELECT INVOICE_NO FROM deleted
    );
END;
GO      